[build]
  publish = "."
  command = "echo 'No build process needed for static PWA'"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[build.environment]
NODE_VERSION = "20.12.2"

# CSS-spezifische Headers hinzufügen
[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/dist/*.css"
  [headers.values]
    Content-Type = "text/css"
    Cache-Control = "public, max-age=31536000"

# Erweiterte SVG-Headers
[[headers]]
  for = "*.svg"
  [headers.values]
    Content-Type = "image/svg+xml"
    Cache-Control = "public, max-age=31536000"
    X-Content-Type-Options = "nosniff"

[[headers]]  
  for = "/images/*.svg"
  [headers.values]
    Content-Type = "image/svg+xml"
    Cache-Control = "public, max-age=31536000"
    Access-Control-Allow-Origin = "*"

# Sicherstellen dass /images/ Verzeichnis korrekt served wird
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Debug-Headers
[[headers]]
  for = "/images/*.svg"
  [headers.values]
    Content-Type = "image/svg+xml"
    X-Debug-SVG = "true"
    Access-Control-Allow-Origin = "*"
