[build]
  publish = "public"
  command = ""

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/health-data"
  to = "/.netlify/functions/health-data"
  status = 200

[[redirects]]
  from = "/api/goals"
  to = "/.netlify/functions/goals"
  status = 200

[[redirects]]
  from = "/api/goals/*"
  to = "/.netlify/functions/goals"
  status = 200

[[redirects]]
  from = "/api/health-data/*"
  to = "/.netlify/functions/health-data"
  status = 200

[build.environment]
NODE_VERSION = "20.12.2"
